/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsContractsRouteImport } from './routes/settings.contracts'
import { Route as AgentsYieldRouteImport } from './routes/agents.yield'
import { Route as AgentsRwaRouteImport } from './routes/agents.rwa'
import { Route as AgentsDaoRouteImport } from './routes/agents.dao'
import { Route as AgentsComplianceRouteImport } from './routes/agents.compliance'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContractsRoute = SettingsContractsRouteImport.update({
  id: '/settings/contracts',
  path: '/settings/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsYieldRoute = AgentsYieldRouteImport.update({
  id: '/agents/yield',
  path: '/agents/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRwaRoute = AgentsRwaRouteImport.update({
  id: '/agents/rwa',
  path: '/agents/rwa',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDaoRoute = AgentsDaoRouteImport.update({
  id: '/agents/dao',
  path: '/agents/dao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsComplianceRoute = AgentsComplianceRouteImport.update({
  id: '/agents/compliance',
  path: '/agents/compliance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/agents/compliance': typeof AgentsComplianceRoute
  '/agents/dao': typeof AgentsDaoRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
  '/settings/contracts': typeof SettingsContractsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/agents/compliance': typeof AgentsComplianceRoute
  '/agents/dao': typeof AgentsDaoRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
  '/settings/contracts': typeof SettingsContractsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/agents/compliance': typeof AgentsComplianceRoute
  '/agents/dao': typeof AgentsDaoRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
  '/settings/contracts': typeof SettingsContractsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/login'
    | '/personas'
    | '/signup'
    | '/sitemap.xml'
    | '/wallet'
    | '/agents/compliance'
    | '/agents/dao'
    | '/agents/rwa'
    | '/agents/yield'
    | '/settings/contracts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/login'
    | '/personas'
    | '/signup'
    | '/sitemap.xml'
    | '/wallet'
    | '/agents/compliance'
    | '/agents/dao'
    | '/agents/rwa'
    | '/agents/yield'
    | '/settings/contracts'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/login'
    | '/personas'
    | '/signup'
    | '/sitemap.xml'
    | '/wallet'
    | '/agents/compliance'
    | '/agents/dao'
    | '/agents/rwa'
    | '/agents/yield'
    | '/settings/contracts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PersonasRoute: typeof PersonasRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WalletRoute: typeof WalletRoute
  AgentsComplianceRoute: typeof AgentsComplianceRoute
  AgentsDaoRoute: typeof AgentsDaoRoute
  AgentsRwaRoute: typeof AgentsRwaRoute
  AgentsYieldRoute: typeof AgentsYieldRoute
  SettingsContractsRoute: typeof SettingsContractsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/contracts': {
      id: '/settings/contracts'
      path: '/settings/contracts'
      fullPath: '/settings/contracts'
      preLoaderRoute: typeof SettingsContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/yield': {
      id: '/agents/yield'
      path: '/agents/yield'
      fullPath: '/agents/yield'
      preLoaderRoute: typeof AgentsYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/rwa': {
      id: '/agents/rwa'
      path: '/agents/rwa'
      fullPath: '/agents/rwa'
      preLoaderRoute: typeof AgentsRwaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/dao': {
      id: '/agents/dao'
      path: '/agents/dao'
      fullPath: '/agents/dao'
      preLoaderRoute: typeof AgentsDaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/compliance': {
      id: '/agents/compliance'
      path: '/agents/compliance'
      fullPath: '/agents/compliance'
      preLoaderRoute: typeof AgentsComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PersonasRoute: PersonasRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WalletRoute: WalletRoute,
  AgentsComplianceRoute: AgentsComplianceRoute,
  AgentsDaoRoute: AgentsDaoRoute,
  AgentsRwaRoute: AgentsRwaRoute,
  AgentsYieldRoute: AgentsYieldRoute,
  SettingsContractsRoute: SettingsContractsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
