/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsYieldRouteImport } from './routes/agents.yield'
import { Route as AgentsRwaRouteImport } from './routes/agents.rwa'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsYieldRoute = AgentsYieldRouteImport.update({
  id: '/agents/yield',
  path: '/agents/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRwaRoute = AgentsRwaRouteImport.update({
  id: '/agents/rwa',
  path: '/agents/rwa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/signup': typeof SignupRoute
  '/agents/rwa': typeof AgentsRwaRoute
  '/agents/yield': typeof AgentsYieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/personas'
    | '/signup'
    | '/agents/rwa'
    | '/agents/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/personas'
    | '/signup'
    | '/agents/rwa'
    | '/agents/yield'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/personas'
    | '/signup'
    | '/agents/rwa'
    | '/agents/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PersonasRoute: typeof PersonasRoute
  SignupRoute: typeof SignupRoute
  AgentsRwaRoute: typeof AgentsRwaRoute
  AgentsYieldRoute: typeof AgentsYieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/yield': {
      id: '/agents/yield'
      path: '/agents/yield'
      fullPath: '/agents/yield'
      preLoaderRoute: typeof AgentsYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/rwa': {
      id: '/agents/rwa'
      path: '/agents/rwa'
      fullPath: '/agents/rwa'
      preLoaderRoute: typeof AgentsRwaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PersonasRoute: PersonasRoute,
  SignupRoute: SignupRoute,
  AgentsRwaRoute: AgentsRwaRoute,
  AgentsYieldRoute: AgentsYieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
